name: build-macos

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*linux.yml'
      - 'docs/**'
      - '.clang-format'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/*linux.yml'
      - 'docs/**'
      - '.clang-format'
      - '.gitignore'
      - 'README.md'
concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: [ macos-11 ]

#    env:
#      BOOST_VERSION: "1.80.0"

    steps:
      - name: Install homebrew
        run: >
          /bin/bash -c "$(curl -fsSL
            https://raw.githubusercontent.com/Homebrew/install/master/install.sh
          )"

      - name: Run brew install
        id: brew-install
        run: |
          brew install \
            boost@1.76 \
            cmake \
            icu4c

      - name: Print toolchain information
        run: |
          git --version
          cc --version
          cmake --version

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}

#      - name: Install boost
#        uses: MarkusJx/install-boost@v2.4.1
#        id: install-boost
#        with:
#            # A list of supported versions can be found here:
#            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
#            boost_version: ${{ env.BOOST_VERSION }}
#            boost_install_dir: ${{ runner.temp }}
#            platform_version: 11
#            toolset: clang
#            arch: x86

      - name: Configure CMake
        env:
          BOOST_ROOT: "/usr/local/Cellar/boost@1.76/1.76.0_3"
          LDFLAGS: "-L/usr/local/opt/icu4c/lib"
          CPPFLAGS: "-I/usr/local/opt/icu4c/include"
        run: |
          cmake -G "Unix Makefiles" \
            -B build \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=Release \
            -DCIRCUIT_ASSEMBLY_OUTPUT=TRUE .

      - name: Build zkllvm
        run: |
          make -C build assigner clang transpiler -j$(sysctl -n hw.logicalcpu)

      - name: Build examples
        run: |
          make -C build circuit_examples -j$(sysctl -n hw.logicalcpu)

      - name: Build circuits
        run: |
          make -C build run_examples -j$(sysctl -n hw.logicalcpu)
