name: build-macos

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*linux.yml'
      - 'docs/**'
      - '.clang-format'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/*linux.yml'
      - 'docs/**'
      - '.clang-format'
      - '.gitignore'
      - 'README.md'
concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: [ macos-11 ]

#    env:
#      BOOST_VERSION: "1.80.0"

    steps:
      - name: Install homebrew
        run: >
          /bin/bash -c "$(curl -fsSL
            https://raw.githubusercontent.com/Homebrew/install/master/install.sh
          )"

      - name: Run brew install
        id: brew-install
        run: |
          brew install \
            boost@1.76 \
            cmake

      - name: Print toolchain information
        run: |
          git --version
          cc --version
          cmake --version
          sysctl -a

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # - name: Enable ccache
      #   uses: hendrikmuhs/ccache-action@v1.2
      #   with:
      #     key: ${{ github.job }}

#      - name: Install boost
#        uses: MarkusJx/install-boost@v2.4.1
#        id: install-boost
#        with:
#            # A list of supported versions can be found here:
#            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
#            boost_version: ${{ env.BOOST_VERSION }}
#            boost_install_dir: ${{ runner.temp }}
#            platform_version: 11
#            toolset: clang
#            arch: x86

      - name: Configure CMake
        env:
          BOOST_ROOT: "/usr/local/Cellar/boost@1.76/1.76.0_3"
        run: |
          cmake -G "Unix Makefiles" \
            -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
            -DCIRCUIT_ASSEMBLY_OUTPUT=TRUE .

      - name: Build zkllvm
        run: |
          make -C build avxtest -j$(sysctl -n hw.logicalcpu)

      - name: Build examples
        run: |
          # make -C build circuit_examples -j$(nproc)
          # ls -al ./build/examples
          grep 1.cpp ./build/compile_commands.json

      - name: Prepare lldb script
        run: |
          echo r >./build/ls.txt
          echo bt >>./build/ls.txt
          echo q >>./build/ls.txt
          lldb --version

      - name: Build circuits
        run: |
          lldb -s ./build/ls.txt -- build/bin/assigner/avxtest
          # make -C build arithmetics_example_run
